mydbt:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: retail_supermarket
      schema: supermarket
      threads: 1
  target: dev
